// =============================================================================
// GridMind Admin — Mock Data for Development
// =============================================================================

import type {
  Agent,
  Approval,
  BillingOverview,
  Deployment,
  FleetHealthSummary,
  Incident,
  StripeSubscription,
  Tenant,
} from "@/types";

export const MOCK_FLEET_HEALTH: FleetHealthSummary = {
  totalAgents: 24,
  healthyAgents: 20,
  degradedAgents: 3,
  offlineAgents: 1,
  openIncidents: 4,
  pendingApprovals: 7,
  p1Incidents: 1,
};

export const MOCK_AGENTS: Agent[] = [
  // Perception tier
  {
    agentId: "argus-001",
    agentName: "argus",
    displayName: "ARGUS",
    tier: "perception",
    status: "healthy",
    autonomyLevel: "autonomous",
    model: "claude-haiku-4-5",
    visibility: "Customer",
    description: "Workload profiler — monitors QPS, latency, and connection patterns.",
    uptimeSeconds: 86400 * 7,
    tasksInFlight: 3,
    tasksCompletedTotal: 14522,
    errorRatePercent: 0.2,
    avgCycleMs: 850,
    lastActionAt: new Date(Date.now() - 60_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 10_000).toISOString(),
  },
  {
    agentId: "oracle-001",
    agentName: "oracle",
    displayName: "ORACLE",
    tier: "perception",
    status: "healthy",
    autonomyLevel: "autonomous",
    model: "claude-haiku-4-5",
    visibility: "Customer",
    description: "Query intelligence — analyzes slow queries and index usage.",
    uptimeSeconds: 86400 * 5,
    tasksInFlight: 1,
    tasksCompletedTotal: 8841,
    errorRatePercent: 0.1,
    avgCycleMs: 1200,
    lastActionAt: new Date(Date.now() - 120_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 8_000).toISOString(),
  },
  {
    agentId: "titan-001",
    agentName: "titan",
    displayName: "TITAN",
    tier: "perception",
    status: "degraded",
    autonomyLevel: "autonomous",
    model: "claude-haiku-4-5",
    visibility: "Customer",
    description: "Infrastructure monitor — tracks CPU, memory, disk, and network.",
    uptimeSeconds: 86400 * 3,
    tasksInFlight: 0,
    tasksCompletedTotal: 5210,
    errorRatePercent: 4.5,
    avgCycleMs: 2100,
    lastActionAt: new Date(Date.now() - 600_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 25_000).toISOString(),
  },
  {
    agentId: "prism-agent-001",
    agentName: "prism_agent",
    displayName: "PRISM-AGENT",
    tier: "perception",
    status: "healthy",
    autonomyLevel: "autonomous",
    model: "claude-haiku-4-5",
    visibility: "Internal",
    description: "Schema drift detector — watches for unauthorized schema changes.",
    uptimeSeconds: 86400 * 6,
    tasksInFlight: 2,
    tasksCompletedTotal: 3201,
    errorRatePercent: 0.0,
    avgCycleMs: 990,
    lastActionAt: new Date(Date.now() - 300_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 9_000).toISOString(),
  },
  {
    agentId: "sentinel-001",
    agentName: "sentinel",
    displayName: "SENTINEL",
    tier: "perception",
    status: "healthy",
    autonomyLevel: "autonomous",
    model: "claude-haiku-4-5",
    visibility: "Customer",
    description: "Security monitor — detects suspicious access patterns and anomalies.",
    uptimeSeconds: 86400 * 14,
    tasksInFlight: 4,
    tasksCompletedTotal: 22400,
    errorRatePercent: 0.3,
    avgCycleMs: 750,
    lastActionAt: new Date(Date.now() - 30_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 5_000).toISOString(),
  },
  {
    agentId: "heimdall-001",
    agentName: "heimdall",
    displayName: "HEIMDALL",
    tier: "perception",
    status: "healthy",
    autonomyLevel: "autonomous",
    model: "claude-haiku-4-5",
    visibility: "Internal",
    description: "Availability monitor — tracks uptime, failovers, and replica lag.",
    uptimeSeconds: 86400 * 21,
    tasksInFlight: 1,
    tasksCompletedTotal: 18920,
    errorRatePercent: 0.1,
    avgCycleMs: 500,
    lastActionAt: new Date(Date.now() - 15_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 4_000).toISOString(),
  },

  // Reasoning tier
  {
    agentId: "sherlock-001",
    agentName: "sherlock",
    displayName: "SHERLOCK",
    tier: "reasoning",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Customer",
    description: "Root cause analyst — investigates incidents using multi-step reasoning.",
    uptimeSeconds: 86400 * 10,
    tasksInFlight: 2,
    tasksCompletedTotal: 892,
    errorRatePercent: 0.5,
    avgCycleMs: 4500,
    lastActionAt: new Date(Date.now() - 90_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 12_000).toISOString(),
  },
  {
    agentId: "herald-001",
    agentName: "herald",
    displayName: "HERALD",
    tier: "reasoning",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Internal",
    description: "Capacity planner — forecasts growth and recommends scaling timelines.",
    uptimeSeconds: 86400 * 8,
    tasksInFlight: 1,
    tasksCompletedTotal: 412,
    errorRatePercent: 0.2,
    avgCycleMs: 6200,
    lastActionAt: new Date(Date.now() - 3600_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 11_000).toISOString(),
  },
  {
    agentId: "comptroller-001",
    agentName: "comptroller",
    displayName: "COMPTROLLER",
    tier: "reasoning",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Customer",
    description: "Cost optimizer — identifies waste and proposes cost reduction actions.",
    uptimeSeconds: 86400 * 12,
    tasksInFlight: 0,
    tasksCompletedTotal: 1022,
    errorRatePercent: 0.0,
    avgCycleMs: 5100,
    lastActionAt: new Date(Date.now() - 7200_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 9_000).toISOString(),
  },
  {
    agentId: "oracle-r-001",
    agentName: "oracle_r",
    displayName: "ORACLE-R",
    tier: "reasoning",
    status: "degraded",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Customer",
    description: "Query optimizer — rewrites slow queries and recommends indexes.",
    uptimeSeconds: 86400 * 2,
    tasksInFlight: 0,
    tasksCompletedTotal: 318,
    errorRatePercent: 8.2,
    avgCycleMs: 7800,
    lastActionAt: new Date(Date.now() - 1800_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 45_000).toISOString(),
  },
  {
    agentId: "axiom-001",
    agentName: "axiom",
    displayName: "AXIOM",
    tier: "reasoning",
    status: "healthy",
    autonomyLevel: "advisory",
    model: "claude-sonnet-4-6",
    visibility: "Customer",
    description: "Compliance advisor — checks configurations against security benchmarks.",
    uptimeSeconds: 86400 * 18,
    tasksInFlight: 0,
    tasksCompletedTotal: 2104,
    errorRatePercent: 0.1,
    avgCycleMs: 3200,
    lastActionAt: new Date(Date.now() - 43200_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 7_000).toISOString(),
  },
  {
    agentId: "cortex-001",
    agentName: "cortex_agent",
    displayName: "CORTEX",
    tier: "reasoning",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Internal",
    description: "Event correlator — links related events across tenants and deployments.",
    uptimeSeconds: 86400 * 30,
    tasksInFlight: 5,
    tasksCompletedTotal: 45210,
    errorRatePercent: 0.4,
    avgCycleMs: 2800,
    lastActionAt: new Date(Date.now() - 20_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 6_000).toISOString(),
  },

  // Execution tier
  {
    agentId: "forge-agent-001",
    agentName: "forge_agent",
    displayName: "FORGE-AGENT",
    tier: "execution",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Internal",
    description: "Index builder — creates and drops indexes based on recommendations.",
    uptimeSeconds: 86400 * 15,
    tasksInFlight: 1,
    tasksCompletedTotal: 540,
    errorRatePercent: 1.1,
    avgCycleMs: 8900,
    lastActionAt: new Date(Date.now() - 900_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 13_000).toISOString(),
  },
  {
    agentId: "convoy-001",
    agentName: "convoy",
    displayName: "CONVOY",
    tier: "execution",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Customer",
    description: "Migration executor — runs schema migrations with zero-downtime strategies.",
    uptimeSeconds: 86400 * 20,
    tasksInFlight: 0,
    tasksCompletedTotal: 128,
    errorRatePercent: 0.8,
    avgCycleMs: 15000,
    lastActionAt: new Date(Date.now() - 86400_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 8_000).toISOString(),
  },
  {
    agentId: "aegis-001",
    agentName: "aegis",
    displayName: "AEGIS",
    tier: "execution",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Customer",
    description: "Backup executor — manages automated backups and validates restore integrity.",
    uptimeSeconds: 86400 * 25,
    tasksInFlight: 2,
    tasksCompletedTotal: 1882,
    errorRatePercent: 0.2,
    avgCycleMs: 3400,
    lastActionAt: new Date(Date.now() - 1200_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 10_000).toISOString(),
  },
  {
    agentId: "titan-x-001",
    agentName: "titan_x",
    displayName: "TITAN-X",
    tier: "execution",
    status: "offline",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Customer",
    description: "Scaling executor — vertically and horizontally scales database instances.",
    uptimeSeconds: 0,
    tasksInFlight: 0,
    tasksCompletedTotal: 244,
    errorRatePercent: 0.0,
    avgCycleMs: 0,
    lastActionAt: new Date(Date.now() - 86400_000 * 2).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 3600_000).toISOString(),
  },
  {
    agentId: "vault-001",
    agentName: "vault_agent",
    displayName: "VAULT",
    tier: "execution",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Internal",
    description: "Secrets rotator — rotates database credentials and SSL certificates.",
    uptimeSeconds: 86400 * 45,
    tasksInFlight: 0,
    tasksCompletedTotal: 88,
    errorRatePercent: 0.0,
    avgCycleMs: 5600,
    lastActionAt: new Date(Date.now() - 604800_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 7_000).toISOString(),
  },
  {
    agentId: "harbor-001",
    agentName: "harbor",
    displayName: "HARBOR",
    tier: "execution",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Customer",
    description: "Connection manager — tunes pool settings and kills zombie connections.",
    uptimeSeconds: 86400 * 9,
    tasksInFlight: 3,
    tasksCompletedTotal: 4400,
    errorRatePercent: 0.6,
    avgCycleMs: 1800,
    lastActionAt: new Date(Date.now() - 180_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 9_000).toISOString(),
  },

  // Self-healing tier
  {
    agentId: "medic-001",
    agentName: "medic",
    displayName: "MEDIC",
    tier: "self_healing",
    status: "healthy",
    autonomyLevel: "autonomous",
    model: "claude-sonnet-4-6",
    visibility: "Internal",
    description: "Agent healer — restarts crashed agents and restores healthy state.",
    uptimeSeconds: 86400 * 60,
    tasksInFlight: 1,
    tasksCompletedTotal: 210,
    errorRatePercent: 0.5,
    avgCycleMs: 2000,
    lastActionAt: new Date(Date.now() - 3600_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 6_000).toISOString(),
  },
  {
    agentId: "phoenix-001",
    agentName: "phoenix",
    displayName: "PHOENIX",
    tier: "self_healing",
    status: "degraded",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Customer",
    description: "Failover orchestrator — triggers and validates automatic failovers.",
    uptimeSeconds: 86400 * 4,
    tasksInFlight: 0,
    tasksCompletedTotal: 12,
    errorRatePercent: 3.2,
    avgCycleMs: 9500,
    lastActionAt: new Date(Date.now() - 7200_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 30_000).toISOString(),
  },
  {
    agentId: "watchdog-001",
    agentName: "watchdog",
    displayName: "WATCHDOG",
    tier: "self_healing",
    status: "healthy",
    autonomyLevel: "autonomous",
    model: "claude-haiku-4-5",
    visibility: "Internal",
    description: "Deadlock resolver — detects and breaks database deadlocks automatically.",
    uptimeSeconds: 86400 * 35,
    tasksInFlight: 0,
    tasksCompletedTotal: 892,
    errorRatePercent: 0.1,
    avgCycleMs: 500,
    lastActionAt: new Date(Date.now() - 43200_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 5_000).toISOString(),
  },
  {
    agentId: "guardian-001",
    agentName: "guardian",
    displayName: "GUARDIAN",
    tier: "self_healing",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Customer",
    description: "Config guardian — detects and rolls back unsafe configuration changes.",
    uptimeSeconds: 86400 * 22,
    tasksInFlight: 0,
    tasksCompletedTotal: 44,
    errorRatePercent: 0.0,
    avgCycleMs: 4200,
    lastActionAt: new Date(Date.now() - 172800_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 8_000).toISOString(),
  },
  {
    agentId: "nexus-001",
    agentName: "nexus",
    displayName: "NEXUS",
    tier: "self_healing",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-sonnet-4-6",
    visibility: "Internal",
    description: "NATS mesh monitor — repairs broken event mesh subscriptions.",
    uptimeSeconds: 86400 * 18,
    tasksInFlight: 0,
    tasksCompletedTotal: 38,
    errorRatePercent: 0.0,
    avgCycleMs: 1200,
    lastActionAt: new Date(Date.now() - 604800_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 7_000).toISOString(),
  },
  {
    agentId: "atlas-agent-001",
    agentName: "atlas_agent",
    displayName: "ATLAS-AGENT",
    tier: "self_healing",
    status: "healthy",
    autonomyLevel: "supervised",
    model: "claude-opus-4-6",
    visibility: "Internal",
    description: "System orchestrator — coordinates cross-agent recovery and health validation.",
    uptimeSeconds: 86400 * 90,
    tasksInFlight: 1,
    tasksCompletedTotal: 88,
    errorRatePercent: 0.0,
    avgCycleMs: 12000,
    lastActionAt: new Date(Date.now() - 86400_000).toISOString(),
    lastHeartbeatAt: new Date(Date.now() - 10_000).toISOString(),
  },
];

export const MOCK_TENANTS: Tenant[] = [
  {
    tenantId: "tenant-001",
    orgName: "Acme Corporation",
    email: "ops@acmecorp.com",
    status: "active",
    tier: "enterprise",
    stripeCustomerId: "cus_acme001",
    stripeSubscriptionId: "sub_acme001",
    mrr: 4999,
    deploymentCount: 8,
    activeAgentCount: 24,
    storageGb: 840,
    storageGbLimit: 2048,
    createdAt: "2025-08-15T09:00:00Z",
    updatedAt: new Date(Date.now() - 3600_000).toISOString(),
  },
  {
    tenantId: "tenant-002",
    orgName: "DataFlow Inc",
    email: "admin@dataflow.io",
    status: "active",
    tier: "professional",
    stripeCustomerId: "cus_df002",
    stripeSubscriptionId: "sub_df002",
    mrr: 1299,
    deploymentCount: 3,
    activeAgentCount: 18,
    storageGb: 180,
    storageGbLimit: 512,
    createdAt: "2025-10-01T14:00:00Z",
    updatedAt: new Date(Date.now() - 7200_000).toISOString(),
  },
  {
    tenantId: "tenant-003",
    orgName: "Startup Labs",
    email: "cto@startuplabs.dev",
    status: "trialing",
    tier: "starter",
    mrr: 0,
    deploymentCount: 1,
    activeAgentCount: 8,
    storageGb: 12,
    storageGbLimit: 50,
    createdAt: "2026-03-10T08:00:00Z",
    updatedAt: new Date(Date.now() - 86400_000).toISOString(),
    trialEndsAt: new Date(Date.now() + 86400_000 * 7).toISOString(),
  },
  {
    tenantId: "tenant-004",
    orgName: "MegaBank Financial",
    email: "dba-team@megabank.com",
    status: "active",
    tier: "enterprise",
    stripeCustomerId: "cus_mb004",
    stripeSubscriptionId: "sub_mb004",
    mrr: 9999,
    deploymentCount: 24,
    activeAgentCount: 24,
    storageGb: 4200,
    storageGbLimit: 10240,
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: new Date(Date.now() - 1800_000).toISOString(),
  },
  {
    tenantId: "tenant-005",
    orgName: "RetailEdge",
    email: "infra@retailedge.com",
    status: "past_due",
    tier: "professional",
    stripeCustomerId: "cus_re005",
    stripeSubscriptionId: "sub_re005",
    mrr: 1299,
    deploymentCount: 5,
    activeAgentCount: 16,
    storageGb: 350,
    storageGbLimit: 512,
    createdAt: "2025-09-15T11:00:00Z",
    updatedAt: new Date(Date.now() - 43200_000).toISOString(),
  },
  {
    tenantId: "tenant-006",
    orgName: "CloudNative Co",
    email: "platform@cloudnative.co",
    status: "suspended",
    tier: "professional",
    stripeCustomerId: "cus_cn006",
    stripeSubscriptionId: "sub_cn006",
    mrr: 0,
    deploymentCount: 2,
    activeAgentCount: 0,
    storageGb: 95,
    storageGbLimit: 512,
    createdAt: "2025-11-20T09:00:00Z",
    updatedAt: new Date(Date.now() - 172800_000).toISOString(),
  },
];

export const MOCK_DEPLOYMENTS: Deployment[] = [
  {
    deploymentId: "deploy-001",
    tenantId: "tenant-001",
    tenantName: "Acme Corporation",
    name: "acme-prod-primary",
    engine: "postgresql",
    status: "running",
    region: "us-east-1",
    instanceType: "db.r6g.2xlarge",
    versionTag: "16.2",
    storageGb: 500,
    connectionCount: 142,
    qps: 8420,
    p95LatencyMs: 4.2,
    cpuPercent: 38,
    memoryPercent: 61,
    createdAt: "2025-08-15T10:00:00Z",
    updatedAt: new Date(Date.now() - 300_000).toISOString(),
  },
  {
    deploymentId: "deploy-002",
    tenantId: "tenant-001",
    tenantName: "Acme Corporation",
    name: "acme-analytics",
    engine: "postgresql",
    status: "running",
    region: "us-east-1",
    instanceType: "db.r6g.4xlarge",
    versionTag: "16.2",
    storageGb: 2000,
    connectionCount: 28,
    qps: 1200,
    p95LatencyMs: 45.0,
    cpuPercent: 22,
    memoryPercent: 45,
    createdAt: "2025-09-01T12:00:00Z",
    updatedAt: new Date(Date.now() - 900_000).toISOString(),
  },
  {
    deploymentId: "deploy-003",
    tenantId: "tenant-002",
    tenantName: "DataFlow Inc",
    name: "dataflow-prod",
    engine: "postgresql",
    status: "degraded",
    region: "eu-west-1",
    instanceType: "db.r6g.xlarge",
    versionTag: "15.4",
    storageGb: 250,
    connectionCount: 89,
    qps: 3100,
    p95LatencyMs: 28.5,
    cpuPercent: 87,
    memoryPercent: 78,
    createdAt: "2025-10-01T15:00:00Z",
    updatedAt: new Date(Date.now() - 60_000).toISOString(),
  },
  {
    deploymentId: "deploy-004",
    tenantId: "tenant-004",
    tenantName: "MegaBank Financial",
    name: "megabank-core",
    engine: "postgresql",
    status: "running",
    region: "us-east-1",
    instanceType: "db.r6g.8xlarge",
    versionTag: "16.2",
    storageGb: 4000,
    connectionCount: 512,
    qps: 45000,
    p95LatencyMs: 2.1,
    cpuPercent: 55,
    memoryPercent: 72,
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: new Date(Date.now() - 120_000).toISOString(),
  },
  {
    deploymentId: "deploy-005",
    tenantId: "tenant-003",
    tenantName: "Startup Labs",
    name: "startup-dev",
    engine: "postgresql",
    status: "running",
    region: "us-west-2",
    instanceType: "db.t4g.medium",
    versionTag: "16.2",
    storageGb: 20,
    connectionCount: 8,
    qps: 45,
    p95LatencyMs: 12.0,
    cpuPercent: 5,
    memoryPercent: 18,
    createdAt: "2026-03-10T09:00:00Z",
    updatedAt: new Date(Date.now() - 3600_000).toISOString(),
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    incidentId: "inc-001",
    tenantId: "tenant-002",
    tenantName: "DataFlow Inc",
    deploymentId: "deploy-003",
    deploymentName: "dataflow-prod",
    title: "High CPU utilization causing query timeouts",
    description:
      "CPU has been sustained above 85% for 23 minutes causing P95 latency to spike from 8ms to 28ms. Active connections are queuing.",
    severity: "P1",
    status: "investigating",
    assignedAgentId: "sherlock-001",
    assignedAgentName: "SHERLOCK",
    affectedComponents: ["postgresql", "connection-pool"],
    createdAt: new Date(Date.now() - 1800_000).toISOString(),
    updatedAt: new Date(Date.now() - 300_000).toISOString(),
    durationMinutes: 30,
  },
  {
    incidentId: "inc-002",
    tenantId: "tenant-004",
    tenantName: "MegaBank Financial",
    deploymentId: "deploy-004",
    deploymentName: "megabank-core",
    title: "Replica lag exceeding threshold on read replica",
    description:
      "Replica lag has reached 8.5 seconds on replica-2, causing stale reads for reporting queries.",
    severity: "P2",
    status: "mitigating",
    assignedAgentId: "phoenix-001",
    assignedAgentName: "PHOENIX",
    affectedComponents: ["replication", "read-replica"],
    createdAt: new Date(Date.now() - 3600_000).toISOString(),
    updatedAt: new Date(Date.now() - 600_000).toISOString(),
    durationMinutes: 60,
  },
  {
    incidentId: "inc-003",
    tenantId: "tenant-001",
    tenantName: "Acme Corporation",
    title: "Scheduled maintenance completed — connection count elevated",
    description:
      "Post-maintenance connection count is 15% higher than baseline. Monitoring for stability.",
    severity: "P3",
    status: "open",
    affectedComponents: ["connection-pool"],
    createdAt: new Date(Date.now() - 7200_000).toISOString(),
    updatedAt: new Date(Date.now() - 3600_000).toISOString(),
    durationMinutes: 120,
  },
  {
    incidentId: "inc-004",
    tenantId: "tenant-005",
    tenantName: "RetailEdge",
    title: "Missing index on orders table causing full scans",
    description:
      "ORACLE-R detected a missing index on orders.customer_id causing sequential scans at 2.1 million rows.",
    severity: "P3",
    status: "resolved",
    assignedAgentId: "forge-agent-001",
    assignedAgentName: "FORGE-AGENT",
    affectedComponents: ["query-performance"],
    rootCause: "Missing composite index on (customer_id, created_at)",
    resolution: "Created index concurrently: CREATE INDEX CONCURRENTLY idx_orders_customer_created",
    createdAt: new Date(Date.now() - 86400_000).toISOString(),
    updatedAt: new Date(Date.now() - 43200_000).toISOString(),
    resolvedAt: new Date(Date.now() - 43200_000).toISOString(),
    durationMinutes: 240,
  },
];

export const MOCK_APPROVALS: Approval[] = [
  {
    approvalId: "appr-001",
    tenantId: "tenant-002",
    tenantName: "DataFlow Inc",
    sourceAgentId: "sherlock-001",
    sourceAgentName: "sherlock",
    sourceAgentDisplayName: "SHERLOCK",
    actionDescription:
      "Restart PostgreSQL connection pool to clear queued connections and reduce CPU load. Estimated 2-3 second interruption.",
    riskLevel: "high",
    context: {
      currentCpu: 87,
      connectionQueue: 48,
      estimatedDowntime: "2-3s",
      deploymentId: "deploy-003",
    },
    status: "pending",
    requestedAt: new Date(Date.now() - 600_000).toISOString(),
    expiresAt: new Date(Date.now() + 3600_000 * 4).toISOString(),
    timeoutSeconds: 300,
  },
  {
    approvalId: "appr-002",
    tenantId: "tenant-001",
    tenantName: "Acme Corporation",
    sourceAgentId: "comptroller-001",
    sourceAgentName: "comptroller",
    sourceAgentDisplayName: "COMPTROLLER",
    actionDescription:
      "Downsize acme-analytics instance from db.r6g.4xlarge to db.r6g.2xlarge during low-traffic window (02:00-04:00 UTC). Estimated monthly savings: $1,840.",
    riskLevel: "medium",
    context: {
      currentInstance: "db.r6g.4xlarge",
      proposedInstance: "db.r6g.2xlarge",
      maxCpuLast30d: 22,
      maxMemoryLast30d: 48,
      estimatedSavingsMonthly: 1840,
    },
    status: "pending",
    requestedAt: new Date(Date.now() - 3600_000).toISOString(),
    expiresAt: new Date(Date.now() + 3600_000 * 20).toISOString(),
    timeoutSeconds: 300,
  },
  {
    approvalId: "appr-003",
    tenantId: "tenant-004",
    tenantName: "MegaBank Financial",
    sourceAgentId: "convoy-001",
    sourceAgentName: "convoy",
    sourceAgentDisplayName: "CONVOY",
    actionDescription:
      "Execute pending schema migration: ADD COLUMN encrypted_ssn bytea to users table. Migration includes zero-downtime strategy with online DDL.",
    riskLevel: "critical",
    context: {
      migrationId: "migration-042",
      tableName: "users",
      rowCount: 8_500_000,
      estimatedDuration: "45 minutes",
      strategy: "online-ddl",
    },
    status: "pending",
    requestedAt: new Date(Date.now() - 1800_000).toISOString(),
    expiresAt: new Date(Date.now() + 3600_000 * 6).toISOString(),
    timeoutSeconds: 300,
  },
  {
    approvalId: "appr-004",
    tenantId: "tenant-005",
    tenantName: "RetailEdge",
    sourceAgentId: "harbor-001",
    sourceAgentName: "harbor",
    sourceAgentDisplayName: "HARBOR",
    actionDescription:
      "Terminate 12 idle connections older than 1 hour to free connection slots for active queries.",
    riskLevel: "low",
    context: {
      idleConnections: 12,
      idleThresholdSeconds: 3600,
      currentPoolSize: 95,
      maxPoolSize: 100,
    },
    status: "pending",
    requestedAt: new Date(Date.now() - 300_000).toISOString(),
    expiresAt: new Date(Date.now() + 3600_000 * 4).toISOString(),
    timeoutSeconds: 300,
  },
  {
    approvalId: "appr-005",
    tenantId: "tenant-001",
    tenantName: "Acme Corporation",
    sourceAgentId: "forge-agent-001",
    sourceAgentName: "forge_agent",
    sourceAgentDisplayName: "FORGE-AGENT",
    actionDescription:
      "Create index CONCURRENTLY on orders(tenant_id, status, created_at) to support new reporting queries. No table lock required.",
    riskLevel: "low",
    context: {
      indexName: "idx_orders_tenant_status_created",
      table: "orders",
      columns: ["tenant_id", "status", "created_at"],
      estimatedDuration: "8 minutes",
    },
    status: "approved",
    requestedAt: new Date(Date.now() - 7200_000).toISOString(),
    expiresAt: new Date(Date.now() + 3600_000).toISOString(),
    respondedAt: new Date(Date.now() - 6900_000).toISOString(),
    respondedBy: "operator@gridmindai.dev",
    justification: "Low-risk concurrent index. Approved.",
    timeoutSeconds: 300,
  },
];

export const MOCK_BILLING_OVERVIEW: BillingOverview = {
  mrrUsd: 87420,
  mrrGrowthPercent: 12.4,
  arrUsd: 1_049_040,
  totalTenants: 42,
  activeTenants: 38,
  avgRevenuePerTenant: 2301,
  grossMarginPercent: 68.5,
  churnRatePercent: 1.2,
};

export const MOCK_SUBSCRIPTIONS: StripeSubscription[] = [
  {
    subscriptionId: "sub_acme001",
    tenantId: "tenant-001",
    tenantName: "Acme Corporation",
    planName: "Enterprise",
    status: "active",
    amountUsd: 4999,
    interval: "month",
    currentPeriodStart: "2026-03-01T00:00:00Z",
    currentPeriodEnd: "2026-04-01T00:00:00Z",
    cancelAtPeriodEnd: false,
  },
  {
    subscriptionId: "sub_df002",
    tenantId: "tenant-002",
    tenantName: "DataFlow Inc",
    planName: "Professional",
    status: "active",
    amountUsd: 1299,
    interval: "month",
    currentPeriodStart: "2026-03-01T00:00:00Z",
    currentPeriodEnd: "2026-04-01T00:00:00Z",
    cancelAtPeriodEnd: false,
  },
  {
    subscriptionId: "sub_mb004",
    tenantId: "tenant-004",
    tenantName: "MegaBank Financial",
    planName: "Enterprise",
    status: "active",
    amountUsd: 9999,
    interval: "month",
    currentPeriodStart: "2026-03-01T00:00:00Z",
    currentPeriodEnd: "2026-04-01T00:00:00Z",
    cancelAtPeriodEnd: false,
  },
  {
    subscriptionId: "sub_re005",
    tenantId: "tenant-005",
    tenantName: "RetailEdge",
    planName: "Professional",
    status: "past_due",
    amountUsd: 1299,
    interval: "month",
    currentPeriodStart: "2026-03-01T00:00:00Z",
    currentPeriodEnd: "2026-04-01T00:00:00Z",
    cancelAtPeriodEnd: false,
  },
];
